# Use the README file as a reference to customize settings.

InvoicedService:
  fields:
    default: service_id, invoice_id
    form: service_id, invoice_id
  relationships: 
  application: Application
